name: Deploy to Vercel


on:
  pull_request:
    branches:
      - dev
      - staging
  push:
    branches:
      - main

jobs:
  install_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install
        working-directory: ./info_web

      - name: Build project
        run: npm run build
        working-directory: ./info_web

  deploy_to_vercel:
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./info_web

      - name: Build project
        run: npm run build
        working-directory: ./info_web

      - name: Deploy to Vercel
        working-directory: ./info_web
        run: |
          npm i -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}  # Use Vercel token stored in GitHub Secrets
